[package]
name = "rooster"
version = "2.7.1"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
license = "Apache-2.0"
repository = "https://github.com/conradkdotcom/rooster"
homepage = "https://github.com/conradkdotcom/rooster"
keywords = ["password", "security"]
description = "A simple password manager for geeks"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rust-crypto = "0.2"
rand = "0.5"
libc = "0.2"
getopts = "0.2"
byteorder = "1.3"
clipboard = "0.5"
rprompt = "1.0"
rpassword = "3.0"
zxcvbn = "1.0"
dirs = "1.0"
