[package]
name = "rooster"
version = "2.9.0"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
license = "Apache-2.0"
repository = "https://github.com/conradkleinespel/rooster"
homepage = "https://github.com/conradkleinespel/rooster"
keywords = ["password", "security"]
description = "A simple password manager for geeks"
links = "sodium"
build = "build.rs"
readme = "README.md"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"
libc = "0.2"
byteorder = "1.3"
clipboard = "0.5"
dirs = "3.0"
openssl = "0.10"
ansi_term = "0.12"
clap = "3.0.0-beta.2"
csv = "1.1"
tempfile = "3.1"
